textLabel("LogInHeader", "Log In");
    setPosition("LogInHeader", 80, 40);
    setProperty("LogInHeader", "font-size", 40);
    setProperty("LogInHeader", "text-align", "center");
    setProperty("LogInHeader", "text-color", "black");
textLabel("Username", "Email");
    setPosition("Username", 0, 110);
    setProperty("Username", "font-size", 12);
    setProperty("Username", "text-align", "left");
textLabel("Password", "Password");
    setPosition("Password", 0, 180);
    setProperty("Password", "font-size", 12);
    setProperty("Password", "text-align", "left");
textInput("UsernameInput", "");
    setPosition("UsernameInput", 10, 130, 300, 30);
textInput("PasswordInput", "");
    setPosition("PasswordInput", 10, 200, 300, 30);
textLabel("PasswordIncorrect", "The Email and Password Do Not Match!");
    setPosition("PasswordIncorrect", 10, 235, 300, 25);
    setProperty("PasswordIncorrect", "background-color", "red");
    setProperty("PasswordIncorrect", "text-color", "white");
    setProperty("PasswordIncorrect", "font-size", "12");
    setProperty("PasswordIncorrect", "text-align", "center");
    hideElement("PasswordIncorrect");
button("Log", "Log In");
    setPosition("Log", 10, 270, 300, 45);
button("ForgotPassword", "Forgot Password?");
    setPosition("ForgotPassword", 10, 330, 300, 45);
button("CreateAccount", "Create Account");
    setPosition("CreateAccount", 10, 390, 300, 45);
appendItem(allUI, "LogInHeader");
appendItem(allUI, "Username");
appendItem(allUI, "Password");
appendItem(allUI, "UsernameInput");
appendItem(allUI, "PasswordInput");
appendItem(allUI, "Log");
appendItem(allUI, "ForgotPassword");
appendItem(allUI, "CreateAccount");
appendItem(allUI,"PasswordIncorrect");