textLabel("SignUpHeader", "Sign Up");
    setPosition("SignUpHeader", 65, 30);
    setProperty("SignUpHeader", "font-size", 40);
    setProperty("SignUpHeader", "text-align", "center");
    setProperty("SignUpHeader", "text-color", "black");
textLabel("Email", "Email");
    setPosition("Email", 0, 100);
    setProperty("Email", "font-size", 12);
    setProperty("Email", "text-align", "left");
textLabel("Username1", "Username");
    setPosition("Username1", 0, 170);
    setProperty("Username1", "font-size", 12);
    setProperty("Username1", "text-align", "left");
textLabel("Password1", "Password");
    setPosition("Password1", 0, 235);
    setProperty("Password1", "font-size", 12);
    setProperty("Password1", "text-align", "left");
textInput("EmailInput", "");
    setPosition("EmailInput", 10, 120, 300, 30);
textInput("UsernameInput1", "");
    setPosition("UsernameInput1", 10, 190, 300, 30);
textInput("PasswordInput1", "");
    setPosition("PasswordInput1", 10, 255, 300, 30);
textLabel("AccountExists", "An Account With This Email Already Exists!");
    setPosition("AccountExists", 10, 288, 300, 25);
    setProperty("AccountExists", "background-color", "red");
    setProperty("AccountExists", "text-color", "white");
    setProperty("AccountExists", "font-size", "11");
    setProperty("AccountExists", "text-align", "center");
    hideElement("AccountExists");
button("Sign", "Sign Up");
    setPosition("Sign", 10, 320, 300, 45);
button("HaveAccount", "Have An Account?");
    setPosition("HaveAccount", 10, 380, 300, 45);
appendItem(allUI, "SignUpHeader");
appendItem(allUI, "Email");
appendItem(allUI, "Username1");
appendItem(allUI, "Password1");
appendItem(allUI, "EmailInput");
appendItem(allUI, "UsernameInput1");
appendItem(allUI, "PasswordInput1");
appendItem(allUI, "Sign");
appendItem(allUI, "HaveAccount");
appendItem(allUI,"AccountExists");